// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/ping.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var ping_default = defineTool({
  name: "ping",
  title: "Ping",
  description: "Simple connectivity check. Returns a pong message with the current server timestamp.",
  inputSchema: {
    message: z.string().optional().describe("Optional message to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ message }) => {
    const reply = message ? `pong: ${message}` : "pong";
    return {
      content: [
        {
          type: "text",
          text: `${reply} (server time: ${(/* @__PURE__ */ new Date()).toISOString()})`
        }
      ]
    };
  }
});

// src/lib/mcp/tools/format-phone.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var format_phone_default = defineTool2({
  name: "format_phone_number",
  title: "Format phone number",
  description: "Normalize a raw phone number by stripping non-digit characters. Returns the digits-only form used by the WhatsApp broadcast manager (e.g. 77713567919).",
  inputSchema: {
    phone: z2.string().min(1).describe("Raw phone input, e.g. '+7 (771) 356-7919'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ phone }) => {
    const digits = phone.replace(/\D+/g, "");
    return {
      content: [{ type: "text", text: digits }],
      structuredContent: { phone: digits, length: digits.length }
    };
  }
});

// src/lib/mcp/tools/render-template.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var render_template_default = defineTool3({
  name: "render_template",
  title: "Render broadcast template",
  description: "Fill a broadcast template that uses {{variable}} placeholders (e.g. {{field_1}}, {{name}}) with the provided variable values. Returns the rendered message plus the list of variables that were not substituted.",
  inputSchema: {
    template: z3.string().min(1).describe("Template body containing {{variable}} placeholders."),
    variables: z3.record(z3.string(), z3.string()).describe("Object mapping variable name (without braces) to its replacement value.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ template, variables }) => {
    const rendered = template.replace(
      /\{\{\s*(\w+)\s*\}\}/g,
      (match, key) => key in variables ? variables[key] : match
    );
    const missing = Array.from(
      new Set(
        Array.from(rendered.matchAll(/\{\{\s*(\w+)\s*\}\}/g)).map((m) => m[1])
      )
    );
    return {
      content: [{ type: "text", text: rendered }],
      structuredContent: { rendered, missing_variables: missing }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "wa-sender-mcp",
  title: "WA Sender MCP",
  version: "0.1.0",
  instructions: "Utility tools for the WA Sender WhatsApp broadcast manager. Use `ping` to verify connectivity, `format_phone_number` to normalize raw phone input to digits-only form, and `render_template` to preview a broadcast message by filling {{variable}} placeholders.",
  tools: [ping_default, format_phone_default, render_template_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
